@isTest
public class EmployeeMileagesForCalculation_Test {
    @isTest
    	public static void testMethod1() {
        EmployeeMileagesForCalculation obj = new EmployeeMileagesForCalculation();
        obj.reimbursementid  = 'a001h000001swsP';
        obj.mileageid = 'a002h000001swsP';
        obj.contactid = 'a003h000001swsP';
        obj.name = 'test';
        obj.month = '02-2019';
        obj.threshold = '20';
        obj.totalMileages ='250';
        obj.approvedMileages = '12';
        obj.isSelected = true;
        obj.managerName = 'Doris';
        obj.isSelectedEmailReminder = true;
    }
}