public with sharing class EmployeeMileages 
{    
    public string maintTyre {get;set;}
    public string fuelRate {get;set;}
    public boolean isSelected {get;set;}
    public boolean isChecked {get;set;}
    public String tripdate {get;set;}
    public String dayofweek {get;set;}
    public String starttime {get;set;}
    public String endtime {get;set;}
    public String status {get;set;}
    public String origin {get;set;}
    public String originname {get;set;}
    public String destination {get;set;}
    public String destinationname {get;set;}
    public String mileage {get;set;}
    public String variableamount{get;set;}
    public String variablerate{get;set;}
    public String approveddate{get;set;}
    public String submitteddate {get;set;}
    public String reimbursementid {get;set;}
    public String month {get;set;}
    public String driverid {get;set;}
    public String totalpending {get;set;}
    public String tracingstyle {get;set;}
    public String emailaddress {get;set;}
    public String totalMileages {get;set;}
    public String totalrejected {get;set;}
    public String notes {get;set;}
    public String id {get;set;}
    public EmployeeMileages() 
    {
        
    }
}